---
- name: Remove old Docker versions
  ansible.builtin.dnf:
    name: docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,docker-logrotate,docker-engine
    state: absent
- name: Install necessary packages
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
- name: Install Podman
  ansible.builtin.dnf:
    name: podman
    state: present
- name: Add Docker's official repository
  ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
- name: Remove Docker
  ansible.builtin.dnf:
    name: docker-ce,docker-ce-cli,containerd.io,docker-compose-plugin,docker-compose
    state: absent
- name: Stop Docker
  ansible.builtin.systemd:
    name: docker
    state: stopped
    enabled: no
- name: Start Podman
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: yes