version: '3'
services:
  node:
    image: loqutus/govnocloud-node
    ports:
      - "6969:6969"
    environment:
      "NODE_LIBVIRT_SOCKET" : "qemu+unix:///system?socket=/run/libvirt/libvirt-sock"
      "NODE_NAME": ${NODE_NAME}
      "NODE_IP": ${NODE_IP}
    volumes:
      - /run/libvirt:/run/libvirt/
      - /var/run/libvirt:/var/run/libvirt
      - /var/run/docker.sock:/var/run/docker.sock