version: '3'
services:
  test:
    image: loqutus/govnocloud-test
    environment:
      "TEST_MASTER_HOST": "master"
      "TEST_MASTER_PORT": "7070"
      "TEST_NODE_NAME": "node"
      "TEST_NODE_IP": "node"
      "TEST_NODE_PORT": "6969"
    depends_on:
      - master
      - node