version: '3'
services:
  node:
    image: loqutus/govnocloud-node
    ports:
      - "6969:6969"
    environment:
      "NODE_LIBVIRT_SOCKET" : "qemu:///system"
      "NODE_NAME": "node1"
      "NODE_IP": "192.168.122.144"
    volumes:
      - /run/libvirt:/run/libvirt/
      - /var/run/libvirt:/var/run/libvirt
      - /run/podman/podman.sock:/run/podman/podman.sock
      - /var/lib/libvirt/images:/var/lib/libvirt/images