version: '3'
services:
  node:
    image: loqutus/govnocloud-node
    ports:
      - "6969:6969"
  etcd:
    image: quay.io/coreos/etcd:v3.2.4
    ports:
      - "2379:2379"
      - "2380:2380"
  master:
    image: loqutus/govnocloud-master
    ports:
      - "7070:7070"
    environment:
      "ETCD_HOST": "etcd"
      "NODES": "node,node,6969"
  web:
    image: loqutus/govnocloud-web
    ports:
      - "8080:8080"
    environment:
      "MASTER_HOST": "master"
