---
- name: Install Docker on Fedora master and nodes
  hosts: master,nodes
  become: yes
  tasks:
    - name: Remove old Docker versions
      ansible.builtin.dnf:
        name: docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,docker-logrotate,docker-engine
        state: absent

    - name: Install necessary packages
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Docker's official repository
      ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker-ce,docker-ce-cli,containerd.io
        state: present

    - name: Start Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
