---
- name: Install libvirt
  ansible.builtin.dnf:
    name: libvirt,qemu-kvm
    state: present
- name: Start libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes