on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: prune
      run: make prune
    - name: ansible
      run: make ansible
    - name: docker
      run: make docker
    - name: deploy
      run: make deploy
    - name: composetest
      run: make composetest
      continue-on-error: true
    - name: composelogs
      run: make composelogs
      continue-on-error: true
    - name: Get exit code
      run: echo "Exit code: ${{ jobs.test.steps.composetest.outputs.exit_code }}"
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   with:
    #     tag_name: v0.0.1
    #     release_name: Release v0.0.1
    #     draft: false
    #     prerelease: false

    # - name: Upload binary
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./bin/govnocloud-linux-amd64
    #     asset_name: govnocloud-linux-amd64
    #     asset_content_type: application/octet-stream
    timeout-minutes: 30