on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: build
      run: make
    timeout-minutes: 60